# -- cooding: utf-8 --
s=input("Введите слово или последовательность цифр(минимум 5 символов)")
print(s[3])
print (s[-2])
print(s[0:5])
print(s[0:-2])
print(s[::2])
print(s[1::2])
print(s[::-1])
print(s[::-2])
print(len(s))